import { randomUUID } from "node:crypto";
import path from "node:path";
import { expect, test } from "@playwright/test";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../../src/generated/prisma/client";
import { createAdminBrowserSession } from "./helpers/session";
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.TEST_DATABASE_URL }) });
test.afterAll(async () => { await prisma.$disconnect(); });
test("Owner reviews and issues a source invoice; payment facts and Customer history stay linked", async ({ page }) => {
  await createAdminBrowserSession(page, prisma, "OWNER"); page.on("dialog", dialog => dialog.accept());
  await page.goto("/admin/finance/settings");
  const before = await prisma.billingInstructions.findUnique({ where: { scope: "DEFAULT" } });
  for (const [label, value] of [["Nama penerbit", "Synthetic Niuva TEST"], ["Alamat penerbit", "Synthetic TEST address only"], ["Email penerbit", "invoice@example.test"], ["Nama bank", "Synthetic TEST Bank"], ["Nama pemilik rekening", "Synthetic TEST Account"], ["Nomor rekening", "00000000000"], ["Instruksi transfer", "Synthetic transfer instructions for TEST only."]]) await page.getByLabel(label!, { exact: true }).fill(value!);
  await page.getByRole("button", { name: "Simpan pengaturan" }).click();
  await expect.poll(async () => (await prisma.billingInstructions.findUnique({ where: { scope: "DEFAULT" } }))?.version).toBe((before?.version ?? 0) + 1);
  const email = `finance-browser-${randomUUID()}@example.test`, customer = await prisma.customer.create({ data: { email, normalizedEmail: email, displayName: "Synthetic Finance Customer" } });
  const order = await prisma.order.create({ data: { customerId: customer.id, orderNumber: `TEST-FIN-BROWSER-${randomUUID()}`, orderType: "RETAIL", customerName: "Synthetic Finance Customer", customerEmail: email, customerPhone: "+628000000000", itemsSubtotalRp: "100000", shippingTotalRp: "0", grandTotalRp: "100000", publicTokenHash: randomUUID() } });
  await page.goto(`/admin/orders/${order.id}`); await page.getByRole("link", { name: "Penagihan pesanan" }).click();
  await page.getByRole("button", { name: "Buat draft untuk ditinjau" }).click(); await page.getByRole("link", { name: /Buka hasil|Buka invoice yang sudah tersedia/ }).click();
  await expect(page.getByRole("heading", { name: "Tinjau draft invoice", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Terbitkan invoice", exact: true }).click();
  await expect(page.getByRole("heading", { name: /^INV-\d{6}-\d{6}$/ })).toBeVisible();
  const invoiceId = new URL(page.url()).pathname.split("/").at(-1)!;
  const downloadEvent = page.waitForEvent("download"); await page.getByRole("link", { name: "Unduh PDF" }).click(); const download = await downloadEvent; await download.saveAs(path.resolve(".local/admin-finance/captures/issued-invoice.pdf"));
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.screenshot({ path: ".local/admin-finance/captures/invoice-1440.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390); await page.screenshot({ path: ".local/admin-finance/captures/invoice-390.png", fullPage: true });
  await page.goto(`/admin/customers/${customer.id}?tab=invoices`); await expect(page.getByRole("link", { name: /^INV-\d{6}-\d{6}$/ })).toHaveAttribute("href", new RegExp(`/admin/finance/invoices/${invoiceId}`));
  const payment = await prisma.paymentAttempt.create({ data: { orderId: order.id, purpose: "ORDER_TOTAL", amountRp: "100000", providerOrderId: `TEST-RECEIPT-${randomUUID()}`, status: "SETTLED", settledAt: new Date(), expiresAt: new Date(Date.now() + 60_000) } });
  await page.goto(`/admin/finance/payments?q=${payment.providerOrderId}&status=CONFIRMED`); await page.getByRole("link", { name: payment.providerOrderId, exact: true }).click();
  await expect(page.getByText("Fakta pembayaran dari provider", { exact: false })).toBeVisible(); await expect(page.getByRole("button", { name: "Simpan koreksi transfer" })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "Buka invoice", exact: true })).toHaveAttribute("href", `/admin/finance/invoices/${invoiceId}`);
});
