import { randomUUID } from "node:crypto";
import { expect, test } from "@playwright/test";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../../src/generated/prisma/client";
import { createAdminBrowserSession } from "./helpers/session";
import { defaultSiteInformation } from "../../src/modules/site-information/defaults";
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.TEST_DATABASE_URL }) });
test.afterAll(async () => { await prisma.$disconnect(); });
test("Admin previews and publishes actual public contact and footer", async ({ page }) => {
  await createAdminBrowserSession(page, prisma, "ADMIN");
  await page.goto("/admin/content/site-information");
  const before = await prisma.siteInformation.findUnique({ where: { scope: "PUBLIC_PROFILE" } });
  const description = `Profil publik fixture ${randomUUID()}`;
  await page.getByLabel("Deskripsi singkat").fill(description);
  await page.getByLabel("Telepon / WhatsApp").fill("+628100000000");
  await page.getByRole("button", { name: "Pratinjau", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Pratinjau informasi publik" })).toBeVisible();
  expect((await prisma.siteInformation.findUnique({ where: { scope: "PUBLIC_PROFILE" } }))?.version).toBe(before?.version);
  await page.getByRole("button", { name: "Terbitkan perubahan" }).click();
  await expect(page.getByRole("status")).toHaveText("Informasi situs berhasil diterbitkan.");
  await page.goto("/");
  await expect(page.locator("footer")).toContainText(description);
  await expect(page.locator("footer a[href='tel:+628100000000']")).toBeVisible();
  await page.goto("/services");
  await expect(page.locator("footer")).toContainText(description);
  await page.goto("/admin/content/site-information");
  await page.getByLabel("Deskripsi singkat").fill(defaultSiteInformation.shortDescription);
  await page.getByLabel("Telepon / WhatsApp").fill(defaultSiteInformation.phone);
  await page.getByRole("button", { name: "Terbitkan perubahan" }).click();
  await expect(page.getByRole("status")).toHaveText("Informasi situs berhasil diterbitkan.");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});
