import type { Metadata } from "next";
import { randomUUID } from "node:crypto";
import Link from "next/link";
import { redirect } from "next/navigation";
import { connection } from "next/server";
import { PublicShell } from "@/components/niuva/public-shell";
import { PrivacyForm } from "@/components/niuva/privacy-form";
import { requireCustomer } from "@/lib/auth/customer";
import { isAppError } from "@/modules/shared/errors";
import { CustomerPrivacyRepository } from "@/modules/customer-privacy/repository";
import { isCustomerPrivacyAvailable, PRIVACY_CONTACT, privacyKindLabels, privacyStatusLabels } from "@/modules/customer-privacy/core";
import { PRIVACY_ERROR_MESSAGES } from "@/modules/customer-privacy/handler";
import { typographySystemTokens as type } from "@/design/typography";

export const metadata: Metadata = { title: "Pusat privasi · Niuva", robots: { index: false, follow: false } };
const date = new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Jakarta" });
export default async function PrivacyPage({ searchParams }: { searchParams: Promise<{ status?: string; error?: string; reference?: string; fields?: string }> }) {
  await connection();
  let customer;
  try { customer = await requireCustomer(); } catch (error) { if (isAppError(error) && error.code === "UNAUTHORIZED") redirect("/login?returnTo=%2Faccount%2Fprivacy"); throw error; }
  const params = await searchParams;
  const available = isCustomerPrivacyAvailable();
  const requests = available ? await new CustomerPrivacyRepository().list(customer.id) : [];
  const initialErrors: Record<string, string> = {};
  if (params.fields) { try { const parsed: unknown = JSON.parse(params.fields); if (parsed && typeof parsed === "object") for (const [key, value] of Object.entries(parsed)) if (["details", "correction"].includes(key) && typeof value === "string") initialErrors[key] = value; } catch { /* Ignore malformed status query. */ } }
  return <PublicShell functionalStatus={available ? "server-backed" : "capability-gated"} scope="account"><main id="main-content" className="mx-auto max-w-public px-5 py-10 sm:px-8 sm:py-16">
    <Link href="/account" className="inline-flex min-h-11 items-center text-sm font-medium text-primary underline underline-offset-4">Kembali ke akun</Link>
    <header className="mt-6 border-b border-border pb-8"><p className="text-sm font-medium text-primary">Akun / Privasi</p><h1 className={`mt-3 ${type.heading.className}`}>Kendali atas data Anda.</h1><p className={`mt-4 text-muted-foreground ${type.body.className}`}>Unduh salinan data, ajukan koreksi, atau tutup akun Niuva secara permanen. Permintaan terkait pesanan tetap ditangani melalui kontak resmi.</p><p className="mt-4 text-sm text-muted-foreground">Tersedia khusus Development lokal dan test. Policy Customer publik masih berupa draf.</p></header>
    {params.error ? <p role="alert" className="mt-6 rounded-lg border border-destructive p-4 text-sm">{PRIVACY_ERROR_MESSAGES[params.error] ?? "Permintaan gagal diproses."}</p> : null}
    {params.status && ["sent", "received"].includes(params.status) ? <p role="status" className="mt-6 rounded-lg border border-border bg-card p-4 text-sm leading-6">{params.status === "sent" ? "Provider menerima pengiriman email konfirmasi. Periksa inbox dan spam; buka tautan pada browser serta sesi ini dalam 15 menit. Penerimaan di inbox belum dikonfirmasi aplikasi." : "Permintaan diterima. Nomor dan status tersedia di bawah."}</p> : null}
    {!available ? <p className="mt-8">Pusat privasi belum aktif pada lingkungan ini. Hubungi <a className="text-primary underline" href={`mailto:${PRIVACY_CONTACT}`}>{PRIVACY_CONTACT}</a>.</p> : <div className="mt-10 grid gap-10 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
      <div className="space-y-10"><section aria-labelledby="export-heading" className="border-b border-border pb-8"><h2 id="export-heading" className={type.subheading.className}>Salinan data</h2><p className="mt-3 text-base leading-6 text-muted-foreground">JSON memuat profil, persetujuan, pesanan, Project Brief, Custom Print, metadata berkas, dan permintaan privasi milik Anda. Komunikasi di luar aplikasi dapat diminta melalui Data tambahan.</p><ul className="my-5 list-disc space-y-2 pl-5 text-sm leading-6 text-muted-foreground"><li>Password, token, kredensial provider, dan tautan berkas privat tidak disertakan.</li><li>Salinan disiapkan setelah Anda mengonfirmasi email dalam sesi ini.</li></ul><PrivacyForm prefix="export-email" mode="email" action="/api/account/privacy/confirmation-email" hidden={{ purpose: "EXPORT" }} label="Minta tautan unduhan" /></section>
        <section aria-labelledby="correction-heading"><h2 id="correction-heading" className={type.subheading.className}>Koreksi data</h2><p className="my-4 text-sm leading-6 text-muted-foreground">Owner memeriksa koreksi. Email login, metode akun, dan transaksi historis tidak diubah otomatis.</p><PrivacyForm prefix="correction" mode="request" action="/api/account/privacy/requests" hidden={{ kind: "CORRECTION", submissionKey: randomUUID() }} initialErrors={initialErrors} fields={[{ name: "details", label: "Data yang salah", kind: "textarea", required: true, help: "Sebutkan bagian data atau nomor pesanan. Jangan kirim password atau token." }, { name: "correction", label: "Koreksi yang diminta", kind: "textarea", required: true }]} label="Ajukan koreksi" /></section>
      </div><div className="space-y-10"><section aria-labelledby="additional-heading" className="border-b border-border pb-8"><h2 id="additional-heading" className={type.subheading.className}>Data tambahan</h2><p className="my-4 text-sm leading-6 text-muted-foreground">Minta komunikasi atau data milik Anda yang belum tercakup JSON. Owner memeriksa kepemilikan dan melindungi data pihak lain. Tenggat akses dan koreksi dihitung 3×24 jam sejak permintaan diterima.</p><PrivacyForm prefix="additional" mode="request" action="/api/account/privacy/requests" hidden={{ kind: "ADDITIONAL", submissionKey: randomUUID() }} initialErrors={initialErrors} fields={[{ name: "details", label: "Data yang ingin Anda peroleh", kind: "textarea", required: true, help: "Jelaskan kanal komunikasi, rentang tanggal, atau referensi yang relevan." }]} label="Minta data tambahan" /></section>
        <section aria-labelledby="closure-heading"><h2 id="closure-heading" className={type.subheading.className}>Tutup akun permanen</h2><p className="mt-3 text-base leading-6 text-muted-foreground">Akses berhenti dan semua sesi dicabut. Profil akun, password, token autentikasi, serta persetujuan akun dihapus. Tidak ada masa pemulihan.</p><p className="my-4 text-sm leading-6 text-muted-foreground">Pesanan, pekerjaan, berkas sesuai kelas retensinya, dan kasus aktif tetap disimpan untuk penyelesaian serta kewajiban pencatatan. Penutupan tidak membatalkan pesanan. Kontak terverifikasi pada transaksi/kasus digunakan untuk tindak lanjut. Akun baru tidak mendapat riwayat lama secara otomatis.</p><p className="mb-5 text-sm font-medium">Unduh data terlebih dahulu jika Anda memerlukannya.</p><PrivacyForm prefix="close-email" mode="email" action="/api/account/privacy/confirmation-email" hidden={{ purpose: "CLOSE" }} label="Minta konfirmasi penutupan" danger /></section>
      </div>
    </div>}
    <section className="mt-12 border-t border-border pt-8" aria-labelledby="requests-heading"><h2 id="requests-heading" className={type.subheading.className}>Permintaan Anda</h2>{requests.length === 0 ? <p className="mt-4 text-muted-foreground">Belum ada permintaan privasi.</p> : <div className="mt-4 divide-y divide-border">{requests.map(row => <article key={row.id} className="py-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="font-semibold">{privacyKindLabels[row.kind]}</h3><p className="mt-2 break-all text-sm text-muted-foreground">{row.referenceNumber}</p></div><p className="text-sm font-medium">{privacyStatusLabels[row.status]}</p></div><p className="mt-3 text-sm text-muted-foreground">Diterima {date.format(row.createdAt)} · Tenggat {date.format(row.dueAt)} WIB</p>{row.details ? <p className="mt-4 whitespace-pre-wrap break-words text-sm leading-6">{row.details}</p> : null}{row.correction ? <p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6">Koreksi: {row.correction}</p> : null}{row.response ? <div className="mt-4 border-l-2 border-primary pl-4"><p className="text-sm font-medium">Tanggapan Owner</p><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6">{row.response}</p></div> : null}{row.contentPurgedAt ? <p className="mt-4 text-sm text-muted-foreground">Isi kasus sudah dibersihkan sesuai retensi. Bukti minimum disimpan sampai batas 30 hari.</p> : null}</article>)}</div>}</section>
    <p className="mt-10 text-sm leading-6 text-muted-foreground">Tindak lanjut setelah akun ditutup atau hak privasi lain: <a className="inline-flex min-h-11 items-center text-primary underline" href={`mailto:${PRIVACY_CONTACT}`}>{PRIVACY_CONTACT}</a> · 085117678901.</p>
  </main></PublicShell>;
}
