"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/auth/admin";
import { toAppErrorLogged } from "@/lib/observability/report";
import type { AdminAction } from "@/app/admin/actions";
import { InvoiceService } from "@/modules/finance/invoice-service";
import { ManualPaymentService } from "@/modules/finance/manual-payment-service";
const text = (form: FormData, key: string) => typeof form.get(key) === "string" ? String(form.get(key)) : "";
function refresh(id?: string) { revalidatePath("/admin/finance"); revalidatePath("/admin/finance/invoices"); revalidatePath("/admin/finance/payments"); revalidatePath("/admin/reports"); revalidatePath("/admin"); if (id) revalidatePath(`/admin/finance/invoices/${id}`); }
const error = (value: unknown, boundary: string) => ({ status: "error" as const, message: toAppErrorLogged(value, { boundary }).message });
export const createInvoiceDraftAction: AdminAction = async (_previous, form) => { try { const kind = text(form, "sourceKind"), sourceId = text(form, "sourceId"); const invoice = await new InvoiceService().createDraft(await requireAdmin(), { source: kind === "B2B" ? { kind, inquiryId: sourceId } : { kind, orderId: sourceId }, idempotencyKey: text(form, "idempotencyKey") }); refresh(invoice.id); return { status: "success", message: "Draft invoice siap ditinjau.", link: `/admin/finance/invoices/${invoice.id}` }; } catch (value) { return error(value, "action:finance.invoice.draft"); } };
export const issueInvoiceAction: AdminAction = async (_previous, form) => { try { const invoice = await new InvoiceService().issue(await requireAdmin(), { invoiceId: text(form, "invoiceId"), expectedVersion: Number(form.get("expectedVersion")), settingsVersion: Number(form.get("settingsVersion")), idempotencyKey: text(form, "idempotencyKey") }); refresh(invoice.id); return { status: "success", message: "Invoice berhasil diterbitkan.", link: `/admin/finance/invoices/${invoice.id}` }; } catch (value) { return error(value, "action:finance.invoice.issue"); } };
export const replaceInvoiceAction: AdminAction = async (_previous, form) => { try { const invoice = await new InvoiceService().replace(await requireAdmin(), { expectedSourceVersion: text(form, "expectedSourceVersion"), invoiceId: text(form, "invoiceId"), expectedVersion: Number(form.get("expectedVersion")), settingsVersion: Number(form.get("settingsVersion")), reason: text(form, "reason"), idempotencyKey: text(form, "idempotencyKey") }); refresh(text(form, "invoiceId")); refresh(invoice.id); return { status: "success", message: "Invoice pengganti diterbitkan dan riwayat tersimpan.", link: `/admin/finance/invoices/${invoice.id}` }; } catch (value) { return error(value, "action:finance.invoice.replace"); } };
export const voidInvoiceAction: AdminAction = async (_previous, form) => { try { const invoice = await new InvoiceService().void(await requireAdmin(), { invoiceId: text(form, "invoiceId"), expectedVersion: Number(form.get("expectedVersion")), reason: text(form, "reason") }); refresh(invoice.id); return { status: "success", message: "Dokumen invoice dibatalkan. Penerimaan uang tetap tersimpan." }; } catch (value) { return error(value, "action:finance.invoice.void"); } };
function paymentInput(form: FormData) { return { paymentId: text(form, "paymentId"), expectedVersion: Number(form.get("expectedVersion")), reason: text(form, "reason"), idempotencyKey: text(form, "idempotencyKey") }; }
export const reverseManualPaymentAction: AdminAction = async (_previous, form) => { try { const payment = await new ManualPaymentService().reverse(await requireAdmin(), paymentInput(form)); refresh(); revalidatePath(`/admin/finance/payments/${text(form, "paymentId")}`); revalidatePath(payment.sourceHref); return { status: "success", message: "Pencatatan transfer dibatalkan; catatan asli tetap tersimpan." }; } catch (value) { return error(value, "action:finance.payment.reverse"); } };
export const correctManualPaymentAction: AdminAction = async (_previous, form) => { try { const payment = await new ManualPaymentService().correct(await requireAdmin(), { ...paymentInput(form), amountRp: text(form, "amountRp"), receivedDate: text(form, "receivedDate"), reference: text(form, "reference"), note: text(form, "note"), confirmed: text(form, "confirmed") === "confirmed" }); refresh(); revalidatePath(`/admin/finance/payments/${text(form, "paymentId")}`); revalidatePath(payment.sourceHref); return { status: "success", message: "Koreksi transfer dicatat dan catatan asli tetap tersimpan.", link: `/admin/finance/payments/${payment.id}` }; } catch (value) { return error(value, "action:finance.payment.correct"); } };
