import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { connection } from "next/server";
import { z } from "zod";
import { AdminPageHeader } from "@/app/admin/admin-page-header";
import { AdminAccessView } from "@/app/admin/admin-access-view";
import { loadAdminPageAccess } from "@/app/admin/admin-page-access";
import { loadAdminRecordLogged } from "@/app/admin/admin-page-failure";
import { AdminDataUnavailableView, AdminShell } from "@/components/niuva/admin-shell";
import { FinanceActionForm } from "@/components/niuva/finance-action-form";
import { FinanceReadService } from "@/modules/finance/read-service";
import { formatFinanceRp, FINANCE_STATE_LABELS } from "@/modules/finance/presentation";
import { normalizeAdminReturnTo } from "@/modules/admin/navigation";
import { correctManualPaymentAction, reverseManualPaymentAction } from "../../actions";
export default async function PaymentDetailPage({ params, searchParams }: Readonly<{ params: Promise<{ id: string }>; searchParams: Promise<Record<string, unknown>> }>) {
  await connection(); const gate = await loadAdminPageAccess({ permission: "FINANCE_READ" }); if (gate.kind === "denied") return <AdminAccessView state={gate.state} />;
  const { id } = await params; if (!z.uuid().safeParse(id).success) notFound();
  const loaded = await loadAdminRecordLogged("page:/admin/finance/payments/[id]", () => new FinanceReadService().payment(gate.access, id), { op: "detail" });
  if (loaded.status === "not-found") notFound(); if (loaded.status !== "found") return <AdminDataUnavailableView active="payments" role={gate.access.profile.role} />;
  const payment = loaded.record, returnTo = normalizeAdminReturnTo((await searchParams).returnTo, "/admin/finance/payments");
  return <AdminShell active="payments" role={gate.access.profile.role}><main id="main-content" className="space-y-6" data-admin-surface="payment-detail"><AdminPageHeader title="Detail pembayaran" description={payment.reference} returnHref={returnTo} returnLabel="Pembayaran" breadcrumbs={[{ label: "Keuangan", href: "/admin/finance" }, { label: "Pembayaran", href: returnTo }, { label: "Detail" }]} /><section className="space-y-4 rounded-xl border border-border bg-card p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-2xl font-semibold tabular-nums">{formatFinanceRp(payment.amountRp)}</h2><span className="rounded-full bg-muted px-3 py-1 text-xs font-medium">{FINANCE_STATE_LABELS[payment.state]}</span></div><p className="text-sm text-muted-foreground">{payment.source === "PROVIDER" ? "Fakta pembayaran dari provider" : "Transfer B2B yang dicocokkan dengan dana masuk"} · {payment.actualDate ? new Date(payment.actualDate).toLocaleDateString("id-ID", { timeZone: "Asia/Jakarta" }) : "Belum terkonfirmasi"}</p>{payment.source === "PROVIDER" ? <p className="text-sm text-muted-foreground">Pembaruan status mengikuti konfirmasi provider. Refund dan exception ditangani melalui pekerjaan order terkait.</p> : null}<div className="flex flex-wrap gap-4"><Link className="inline-flex min-h-11 items-center text-sm text-brand-700 underline" href={payment.sourceHref}>Buka sumber pekerjaan</Link>{payment.invoiceId ? <Link className="inline-flex min-h-11 items-center text-sm text-brand-700 underline" href={`/admin/finance/invoices/${payment.invoiceId}`}>Buka invoice</Link> : null}{payment.reversalOfId ? <Link className="inline-flex min-h-11 items-center text-sm text-brand-700 underline" href={`/admin/finance/payments/${payment.reversalOfId}`}>Catatan asli</Link> : null}{payment.correctionId ? <Link className="inline-flex min-h-11 items-center text-sm text-brand-700 underline" href={`/admin/finance/payments/${payment.correctionId}`}>Hasil koreksi</Link> : null}</div>{payment.reason ? <p className="text-sm text-muted-foreground">Alasan: {payment.reason}</p> : null}</section>
    {payment.source === "MANUAL" && payment.state === "CONFIRMED" && payment.caseVersion && payment.sourceHref !== "/admin/finance/payments" ? <div className="grid min-w-0 gap-5 xl:grid-cols-2"><section className="min-w-0 space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Koreksi pencatatan transfer</h2><FinanceActionForm action={correctManualPaymentAction} hidden={{ paymentId: id, expectedVersion: String(payment.caseVersion), idempotencyKey: randomUUID() }} fields={[{ name: "receivedDate", label: "Tanggal dana diterima", type: "date", value: payment.actualDate?.slice(0, 10), required: true }, { name: "amountRp", label: "Nominal diterima (Rp)", value: payment.amountRp, required: true }, { name: "reference", label: "Referensi transfer", value: payment.reference, required: true, maxLength: 100 }, { name: "note", label: "Catatan (opsional)", type: "textarea" }, { name: "reason", label: "Alasan koreksi transfer", type: "textarea", required: true }, { name: "confirmed", label: "Saya telah memeriksa kembali dana yang masuk", type: "checkbox", required: true }]} submitLabel="Simpan koreksi transfer" confirmMessage="Koreksi pencatatan transfer ini dengan alasan yang ditulis? Catatan asli tetap tersimpan." /></section><section className="min-w-0 space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Batalkan pencatatan transfer</h2><p className="text-sm text-muted-foreground">Tindakan ini mengoreksi buku penerimaan. Pengembalian dana dilakukan terpisah.</p><FinanceActionForm action={reverseManualPaymentAction} hidden={{ paymentId: id, expectedVersion: String(payment.caseVersion), idempotencyKey: randomUUID() }} fields={[{ name: "reason", label: "Alasan pembatalan transfer", type: "textarea", required: true }]} submitLabel="Batalkan pencatatan transfer" confirmMessage={`Batalkan pencatatan ${formatFinanceRp(payment.amountRp)}? Dana tidak dikembalikan otomatis.`} /></section></div> : null}
  </main></AdminShell>;
}
