import Link from "next/link";
import { BriefcaseBusiness, Printer, ShoppingBag, TriangleAlert, ArrowUpRight } from "lucide-react";
import { AdminShell } from "@/components/niuva/admin-shell";
import { AdminTrendChart } from "@/components/niuva/admin-trend-chart";
import { AdminPageHeader } from "./admin-page-header";
import type { AdminRole } from "@/generated/prisma/client";
import type { AdminOverviewData } from "@/modules/admin/overview-types";
const card = "min-w-0 rounded-xl border border-border bg-card p-5 sm:p-6";
const money = (value: string) => "Rp " + new Intl.NumberFormat("id-ID").format(BigInt(value));
const time = (value: string | Date) => new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Jakarta" }).format(new Date(value));
export function AdminOverviewView({ data, role }: Readonly<{ data: AdminOverviewData; role: AdminRole }>) {
  const { range, attention, finance, paidOrders, activity, traffic } = data;
  const queue = attention.status === "ok" ? attention.data : null;
  const cards = [
    { title: "B2B perlu ditindaklanjuti", value: queue?.summary.groups.inquiries, href: "/admin/inquiries?view=needs-action", note: "Tinjau brief proyek baru", icon: BriefcaseBusiness },
    { title: "Custom Print perlu tindakan", value: queue?.summary.groups["custom-print"], href: "/admin/custom-print?view=needs-action", note: "Review, siapkan, atau kirim quote", icon: Printer },
    { title: "Order perlu tindakan", value: queue?.summary.groups.orders, href: "/admin/orders?view=needs-action", note: "Proses, ukur paket, atau periksa", icon: ShoppingBag },
    { title: "Isu / perlu perhatian", value: queue?.summary.exceptions, href: queue?.summary.exceptions ? "#admin-issues" : "/admin/orders?view=issues", note: "Pembayaran dan pengiriman", icon: TriangleAlert },
  ];
  return <AdminShell role={role} active="overview"><main id="main-content" data-admin-surface="overview" className="min-w-0 space-y-5">
    <AdminPageHeader title="Overview" description="Pantau pekerjaan hari ini dan ringkasan bisnis Niuva." breadcrumbs={[{ label: "Overview" }]} actions={<div className="flex gap-2">{(["30d", "13m"] as const).map(value => <Link key={value} href={value === "30d" ? "/admin" : "/admin?range=13m"} aria-current={range === value ? "page" : undefined} className={`min-h-11 rounded-lg border border-border px-3 py-3 text-sm ${range === value ? "bg-primary text-primary-foreground" : "bg-card"}`}>{value === "30d" ? "30 hari" : "13 bulan"}</Link>)}</div>} />
    <p className="text-xs text-muted-foreground">Diperbarui {time(data.generatedAt)} WIB · Kartu perhatian menampilkan pekerjaan yang masih terbuka.</p>
    <section aria-label="Pekerjaan perlu perhatian saat ini" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(item => <Link key={item.title} href={item.href} className={`${card} group block transition-colors hover:border-primary/40 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50 motion-reduce:transition-none`}><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium">{item.title}</span><item.icon className="size-5 shrink-0 text-primary" aria-hidden /></div><p className="mt-4 text-3xl font-semibold tabular-nums">{item.value ?? "—"}</p><div className="mt-3 flex items-center justify-between gap-2 text-xs text-muted-foreground"><span>{item.note}</span><ArrowUpRight className="size-4 shrink-0 text-primary" aria-hidden /></div></Link>)}</section>
    {attention.status === "unavailable" && <p role="status" className="rounded-lg border border-border bg-card p-4 text-sm">{attention.message}</p>}
    {queue && queue.summary.exceptions > 0 && <section id="admin-issues" className={card} aria-labelledby="issue-title"><div className="flex flex-wrap justify-between gap-3"><h2 id="issue-title" className="text-lg font-semibold">Perlu pemeriksaan sekarang</h2><Link href="/admin/orders?view=issues" className="text-sm font-medium text-primary">Lihat semua isu</Link></div><ul className="mt-3 divide-y divide-border">{queue.priorityItems.filter(item => item.attention === "EXCEPTION").map(item => <li key={item.id}><Link href={item.href} className="flex min-h-11 flex-wrap items-center justify-between gap-2 py-3 text-sm focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50"><span className="font-medium">{item.title}</span><span className="text-muted-foreground">{item.reference}</span></Link></li>)}</ul></section>}
    <div className="grid min-w-0 gap-4 xl:grid-cols-[minmax(0,1.7fr)_minmax(0,1fr)]">
      <section className={card} aria-labelledby="business-title"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="business-title" className="text-xl font-semibold">Ringkasan bisnis</h2><Link href={`/admin/reports?tab=finance&range=${range}`} className="inline-flex min-h-11 items-center text-sm font-medium text-primary">Lihat laporan</Link></div><p className="mt-1 text-xs text-muted-foreground">{range === "30d" ? "30 hari" : "13 bulan"} terakhir · tanggal transaksi, waktu Jakarta</p><dl className="mt-5 grid gap-5 sm:grid-cols-3"><div><dt className="text-xs text-muted-foreground">Penerimaan terkonfirmasi (bruto)</dt><dd className="mt-2 break-words text-xl font-semibold">{finance.status === "ok" ? money(finance.data.grossConfirmedReceiptsRp) : "—"}</dd></div><div><dt className="text-xs text-muted-foreground">Pengeluaran tercatat</dt><dd className="mt-2 break-words text-xl font-semibold">{finance.status === "ok" ? money(finance.data.validExpensesRp) : "—"}</dd></div><div><dt className="text-xs text-muted-foreground">Order dibayar</dt><dd className="mt-2 text-xl font-semibold">{paidOrders.status === "ok" ? paidOrders.data : "—"}</dd></div></dl>
      {finance.status === "ok" ? <><AdminTrendChart label="Penerimaan terkonfirmasi" unit="Rp" points={finance.data.points.map(point => ({ key: point.key, value: point.receiptsRp }))} /><p className="mt-2 text-xs text-muted-foreground">Penerbitan invoice tidak menambah penerimaan. Nilai bruto belum dikurangi refund.</p>{finance.data.needsReviewCount > 0 && <Link className="mt-3 block text-sm text-primary" href="/admin/finance/payments?status=REVIEW">{finance.data.needsReviewCount} isu pembayaran provider perlu diperiksa saat ini</Link>}</> : <p role="status" className="mt-5 text-sm">{finance.message}</p>}
      {paidOrders.status === "unavailable" && <p role="status" className="mt-3 text-sm">Hitungan order dibayar belum dapat dimuat.</p>}</section>
      <aside className={card} aria-labelledby="activity-title"><div className="flex items-center justify-between gap-3"><h2 id="activity-title" className="text-xl font-semibold">Aktivitas terbaru</h2><Link href="/admin/activity" className="inline-flex min-h-11 items-center text-sm font-medium text-primary">Lihat semua</Link></div>{activity.status === "unavailable" ? <p role="status" className="mt-4 text-sm">{activity.message}</p> : activity.data.items.length === 0 ? <p className="mt-4 text-sm text-muted-foreground">Belum ada aktivitas tercatat.</p> : <ol className="mt-2 divide-y divide-border">{activity.data.items.slice(0, 5).map(item => <li key={item.id} className="py-3">{item.href ? <Link href={item.href} className="block text-sm font-medium text-foreground hover:text-primary focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50">{item.title}</Link> : <p className="text-sm font-medium">{item.title}</p>}<p className="mt-1 text-xs leading-5 text-muted-foreground">{item.group} · {time(item.createdAt)}</p></li>)}</ol>}</aside>
    </div>
    <section className={card} aria-labelledby="traffic-title"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="traffic-title" className="text-xl font-semibold">Trafik situs</h2><Link href={`/admin/reports?tab=traffic&range=${range}`} className="inline-flex min-h-11 items-center text-sm font-medium text-primary">Lihat rincian</Link></div>{traffic.status === "unavailable" ? <p role="status" className="mt-4 text-sm">{traffic.message}</p> : <div className="mt-4 grid gap-5 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Tayangan halaman</p><p className="mt-2 text-2xl font-semibold">{traffic.data.report.pageViews}</p>{!traffic.data.collectionEnabled && <p className="mt-2 text-xs text-muted-foreground">Pengumpulan tayangan belum aktif; data historis ditampilkan bila tersedia.</p>}{traffic.data.collectionEnabled && traffic.data.report.pageViews === 0 && <p className="mt-2 text-xs text-muted-foreground">Belum ada tayangan tercatat.</p>}</div><div><h3 className="text-sm font-medium">Sumber masuk teratas</h3><p className="mt-2 text-sm text-muted-foreground">{traffic.data.report.sources[0] ? `${traffic.data.report.sources[0].key} · ${traffic.data.report.sources[0].count} tayangan pertama` : "Belum ada data."}</p></div><div><h3 className="text-sm font-medium">Perangkat teratas</h3><p className="mt-2 text-sm text-muted-foreground">{traffic.data.report.devices[0] ? `${traffic.data.report.devices[0].key} · ${traffic.data.report.devices[0].count} tayangan` : "Belum ada data."}</p><p className="mt-2 text-xs text-muted-foreground">Kategori agregat; hitungan tayangan bukan pengunjung unik.</p></div></div>}</section>
  </main></AdminShell>;
}
