import { Card } from "@/components/ui/card";
import { buttonVariants } from "@/components/ui/button";
import Link from "next/link";
import { AdminShell } from "@/components/niuva/admin-shell";
import { AdminPageHeader } from "../admin-page-header";
import { AdminTrendChart } from "@/components/niuva/admin-trend-chart";
import type { AdminRole } from "@/generated/prisma/client";
import { reportTabs, type AdminReportsData, type AdminReportTab } from "@/modules/admin/reports/types";
const labels: Record<AdminReportTab, string> = { summary: "Ringkasan", orders: "Orders", "custom-print": "Custom Print", b2b: "B2B", finance: "Keuangan", traffic: "Trafik Situs" };
const card = "gap-0 py-0 ring-0 min-w-0 rounded-xl border border-border bg-card p-5 sm:p-6";
const money = (value: string) => "Rp " + new Intl.NumberFormat("id-ID").format(BigInt(value));
export function AdminReportView({ data, role }: { data: AdminReportsData; role: AdminRole }) {
  const { tab, range, operations, finance, traffic } = data;
  return <AdminShell active="reports" role={role}><main id="main-content" className="space-y-6"><AdminPageHeader title="Laporan" description="Rincian operasional, transaksi keuangan, dan trafik situs. Semua periode memakai waktu Jakarta." breadcrumbs={[{ label: "Laporan" }]} actions={<div className="flex gap-2">{(["30d", "13m"] as const).map(value => <Link key={value} href={`/admin/reports?tab=${tab}&range=${value}`} aria-current={range === value ? "page" : undefined} className={buttonVariants({ variant: range === value ? "default" : "outline" })}>{value === "30d" ? "30 hari" : "13 bulan"}</Link>)}</div>} />
    <nav aria-label="Bagian laporan" className="flex flex-wrap gap-2">{reportTabs.map(value => <Link key={value} href={`/admin/reports?tab=${value}&range=${range}`} aria-current={tab === value ? "page" : undefined} className={buttonVariants({ variant: tab === value ? "default" : "outline" })}>{labels[value]}</Link>)}</nav>
    <p className="text-xs text-muted-foreground">Diperbarui {new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Jakarta" }).format(new Date(data.generatedAt))} WIB</p>
    {(["summary", "orders", "custom-print", "b2b"] as string[]).includes(tab) && <Card as="section" className={card} aria-labelledby="report-operations"><h2 id="report-operations" className="text-xl font-semibold">Operasional</h2>{operations.status === "unavailable" ? <p role="status" className="mt-4 text-sm">{operations.message}</p> : <><dl className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[["Order dibuat", operations.data.createdOrders], ["Order dibayar", operations.data.paidOrders], ["Request Custom Print", operations.data.customPrint], ["Brief B2B masuk", operations.data.briefs]].map(([label, value]) => <div key={label}><dt className="text-sm text-muted-foreground">{label}</dt><dd className="mt-2 text-2xl font-semibold">{value}</dd></div>)}</dl><p className="mt-4 text-sm text-muted-foreground">Order dibuat, request, dan brief mengikuti tanggal dibuat. Order dibayar mengikuti waktu pembayaran pertama terkonfirmasi; status pekerjaan sesudahnya tidak mengubah hitungan ini.</p><AdminTrendChart label={tab === "b2b" ? "Brief B2B masuk" : tab === "custom-print" ? "Request Custom Print" : "Order dibayar"} points={operations.data.points.map(point => ({ key: point.key, value: String(tab === "b2b" ? point.briefs : tab === "custom-print" ? point.customPrint : point.paidOrders) }))} /></>}</Card>}
    {(tab === "summary" || tab === "finance") && <Card as="section" className={card} aria-labelledby="report-finance"><h2 id="report-finance" className="text-xl font-semibold">Keuangan</h2>{finance.status === "unavailable" ? <p role="status" className="mt-4 text-sm">{finance.message}</p> : <><dl className="mt-5 grid gap-5 sm:grid-cols-2"><div><dt className="text-sm text-muted-foreground">Penerimaan terkonfirmasi (bruto)</dt><dd className="mt-2 text-2xl font-semibold">{money(finance.data.grossConfirmedReceiptsRp)}</dd></div><div><dt className="text-sm text-muted-foreground">Pengeluaran tercatat</dt><dd className="mt-2 text-2xl font-semibold">{money(finance.data.validExpensesRp)}</dd></div></dl><p className="mt-4 text-sm text-muted-foreground">Penerimaan mengikuti tanggal dana terkonfirmasi. Pengeluaran mengikuti tanggal transaksi yang dicatat dan hanya entri yang masih berlaku. Penerbitan invoice tidak menambah penerimaan. Ringkasan ini belum merupakan laba akuntansi atau saldo rekening.</p>{finance.data.needsReviewCount > 0 && <p className="mt-3 rounded-lg bg-warning-background p-3 text-sm">{finance.data.needsReviewCount} isu pembayaran provider perlu diperiksa saat ini. Penerimaan ditampilkan bruto; nilai refund parsial yang belum diketahui tidak diperkirakan.</p>}<AdminTrendChart label="Penerimaan terkonfirmasi" unit="Rp" points={finance.data.points.map(point => ({ key: point.key, value: point.receiptsRp }))} />{tab === "finance" && <AdminTrendChart label="Pengeluaran tercatat" unit="Rp" points={finance.data.points.map(point => ({ key: point.key, value: point.expensesRp }))} />}<div className="mt-4 flex flex-wrap gap-4 text-sm text-primary"><Link className={buttonVariants({ variant: "link", className: "px-0" })} href="/admin/finance/payments">Lihat pembayaran</Link><Link className={buttonVariants({ variant: "link", className: "px-0" })} href="/admin/finance/expenses">Lihat pengeluaran</Link></div></>}</Card>}
    {(tab === "summary" || tab === "traffic") && <Card as="section" className={card} aria-labelledby="report-traffic"><h2 id="report-traffic" className="text-xl font-semibold">Trafik Situs</h2>{traffic.status === "unavailable" ? <p role="status" className="mt-4 text-sm">{traffic.message}</p> : <><p className="mt-4 text-3xl font-semibold">{traffic.data.report.pageViews} <span className="text-sm font-normal text-muted-foreground">tayangan halaman</span></p>{!traffic.data.collectionEnabled && <p className="mt-3 rounded-lg bg-muted p-3 text-sm">Pengumpulan tayangan belum aktif. Data historis tetap ditampilkan bila tersedia.</p>}{traffic.data.report.pageViews === 0 && <p className="mt-3 text-sm text-muted-foreground">Belum ada tayangan tercatat pada periode ini.</p>}<p className="mt-3 text-sm text-muted-foreground">Hitungan agregat halaman publik, bukan pengunjung unik atau atribusi order. Bot dan pemblokir dapat memengaruhi jumlah.</p><AdminTrendChart label="Tayangan halaman" points={traffic.data.report.points.map(point => ({ key: point.key, value: String(point.pageViews) }))} />{tab === "traffic" && <div className="mt-5 grid gap-4 sm:grid-cols-2">{[["Sumber masuk", traffic.data.report.sources], ["Perangkat", traffic.data.report.devices], ["Negara", traffic.data.report.countries], ["Kelompok halaman", traffic.data.report.routes]].map(([title, rows]) => <Card as="section" key={String(title)} className="gap-0 py-0 ring-0 rounded-xl border border-border p-4"><h3 className="font-semibold">{String(title)}</h3><p className="mt-2 text-xs text-muted-foreground">{title === "Sumber masuk" ? "Sumber saat halaman pertama dimuat." : title === "Negara" ? "Kode lokasi dari header bila tersedia; ZZ berarti tidak diketahui." : "Kategori agregat tayangan halaman."}</p><ul className="mt-3 space-y-2 text-sm">{typeof rows !== "string" && rows.map(row => <li key={row.key} className="flex justify-between gap-3"><span>{row.key}</span><span>{row.count}</span></li>)}{rows.length === 0 && <li className="text-muted-foreground">Belum ada data.</li>}</ul></Card>)}</div>}</>}</Card>}
  </main></AdminShell>;
}
