import Link from "next/link";
import type { AdminRootPath } from "@/modules/admin/navigation";
import type { FinanceListQuery } from "@/modules/finance/read-query";
import { EXPENSE_CATEGORIES } from "@/modules/finance/expense-categories";
import { FINANCE_STATE_LABELS } from "@/modules/finance/presentation";
const control = "min-h-11 w-full min-w-0 rounded-lg border border-input bg-background px-3 text-sm text-foreground outline-none focus-visible:ring-3 focus-visible:ring-ring/50";
export function FinanceListControls({ target, query, statuses, services = false, expenses = false }: Readonly<{ target: AdminRootPath; query: FinanceListQuery; statuses: readonly string[]; services?: boolean; expenses?: boolean }>) {
  return <form action={target} role="search" aria-label="Filter keuangan" className="grid min-w-0 gap-3 rounded-xl border border-border bg-card p-4 sm:grid-cols-2 xl:grid-cols-4"><label className="grid min-w-0 gap-2 text-xs text-muted-foreground">Cari referensi / keterangan<input className={control} type="search" name="q" maxLength={100} defaultValue={query.q} /></label><label className="grid gap-2 text-xs text-muted-foreground">Status<select className={control} name="status" defaultValue={query.status ?? ""}><option value="">Semua status</option>{statuses.map(status => <option key={status} value={status}>{FINANCE_STATE_LABELS[status] ?? status}</option>)}</select></label>{services ? <label className="grid gap-2 text-xs text-muted-foreground">Layanan<select className={control} name="service" defaultValue={query.service ?? ""}><option value="">Semua layanan</option><option value="ready-made">Ready-made</option><option value="custom-print">Custom Print</option><option value="b2b">B2B</option></select></label> : null}{expenses ? <label className="grid gap-2 text-xs text-muted-foreground">Kategori<select className={control} name="category" defaultValue={query.category ?? ""}><option value="">Semua kategori</option>{Object.entries(EXPENSE_CATEGORIES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label> : null}<label className="grid gap-2 text-xs text-muted-foreground">Dari tanggal<input className={control} type="date" name="dateFrom" defaultValue={query.dateFrom} /></label><label className="grid gap-2 text-xs text-muted-foreground">Sampai tanggal<input className={control} type="date" name="dateTo" defaultValue={query.dateTo} /></label><div className="flex flex-wrap items-end gap-3"><button className="min-h-11 rounded-lg bg-brand-700 px-4 text-sm font-semibold text-white" type="submit">Terapkan filter</button><Link className="inline-flex min-h-11 items-center text-sm text-muted-foreground underline" href={target}>Reset</Link></div></form>;
}
