import { Label } from "@/components/ui/label";
import { NativeInput as Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import type { AdminRootPath } from "@/modules/admin/navigation";
import type { FinanceListQuery } from "@/modules/finance/read-query";
import { EXPENSE_CATEGORIES } from "@/modules/finance/expense-categories";
import { FINANCE_STATE_LABELS } from "@/modules/finance/presentation";
const control = "min-h-11 w-full min-w-0 rounded-lg border border-input bg-background px-3 text-sm text-foreground outline-none focus-visible:ring-3 focus-visible:ring-ring/50";
export function FinanceListControls({ target, query, statuses, services = false, expenses = false }: Readonly<{ target: AdminRootPath; query: FinanceListQuery; statuses: readonly string[]; services?: boolean; expenses?: boolean }>) {
  return <form action={target} role="search" aria-label="Filter keuangan" className="grid min-w-0 gap-3 rounded-xl border border-border bg-card p-4 sm:grid-cols-2 xl:grid-cols-4"><Label className="grid min-w-0 gap-2 text-xs text-muted-foreground">Cari referensi / keterangan<Input className={control} type="search" name="q" maxLength={100} defaultValue={query.q} /></Label><Label className="grid gap-2 text-xs text-muted-foreground">Status<NativeSelect className={control} name="status" defaultValue={query.status ?? ""}><NativeSelectOption value="">Semua status</NativeSelectOption>{statuses.map(status => <NativeSelectOption key={status} value={status}>{FINANCE_STATE_LABELS[status] ?? status}</NativeSelectOption>)}</NativeSelect></Label>{services ? <Label className="grid gap-2 text-xs text-muted-foreground">Layanan<NativeSelect className={control} name="service" defaultValue={query.service ?? ""}><NativeSelectOption value="">Semua layanan</NativeSelectOption><NativeSelectOption value="ready-made">Ready-made</NativeSelectOption><NativeSelectOption value="custom-print">Custom Print</NativeSelectOption><NativeSelectOption value="b2b">B2B</NativeSelectOption></NativeSelect></Label> : null}{expenses ? <Label className="grid gap-2 text-xs text-muted-foreground">Kategori<NativeSelect className={control} name="category" defaultValue={query.category ?? ""}><NativeSelectOption value="">Semua kategori</NativeSelectOption>{Object.entries(EXPENSE_CATEGORIES).map(([value, label]) => <NativeSelectOption key={value} value={value}>{label}</NativeSelectOption>)}</NativeSelect></Label> : null}<Label className="grid gap-2 text-xs text-muted-foreground">Dari tanggal<Input className={control} type="date" name="dateFrom" defaultValue={query.dateFrom} /></Label><Label className="grid gap-2 text-xs text-muted-foreground">Sampai tanggal<Input className={control} type="date" name="dateTo" defaultValue={query.dateTo} /></Label><div className="flex flex-wrap items-end gap-3"><Button variant="default" className="min-h-11 rounded-lg bg-brand-700 px-4 text-sm font-semibold text-white" type="submit">Terapkan filter</Button><Link className="inline-flex min-h-11 items-center text-sm text-muted-foreground underline" href={target}>Reset</Link></div></form>;
}
