import { Card } from "@/components/ui/card";
import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { connection } from "next/server";
import { z } from "zod";
import { AdminPageHeader } from "@/app/admin/admin-page-header";
import { AdminAccessView } from "@/app/admin/admin-access-view";
import { loadAdminPageAccess } from "@/app/admin/admin-page-access";
import { loadAdminRecordLogged } from "@/app/admin/admin-page-failure";
import { AdminDataUnavailableView, AdminShell } from "@/components/niuva/admin-shell";
import { FinanceActionForm } from "@/components/niuva/finance-action-form";
import { buildInvoiceFinancialSnapshot } from "@/modules/finance/invoice-document";
import { FinanceReadService } from "@/modules/finance/read-service";
import { BillingSettingsService } from "@/modules/finance/billing-settings-service";
import { normalizeAdminReturnTo, adminRootLabel } from "@/modules/admin/navigation";
import { formatFinanceRp, FINANCE_STATE_LABELS, invoicePaymentInstructions } from "@/modules/finance/presentation";
import { issueInvoiceAction, replaceInvoiceAction, voidInvoiceAction } from "../../actions";
export default async function InvoiceDetailPage({ params, searchParams }: Readonly<{ params: Promise<{ id: string }>; searchParams: Promise<Record<string, unknown>> }>) {
  await connection(); const gate = await loadAdminPageAccess({ permission: "FINANCE_READ" }); if (gate.kind === "denied") return <AdminAccessView state={gate.state} />;
  const { id } = await params; if (!z.uuid().safeParse(id).success) notFound();
  const loaded = await loadAdminRecordLogged("page:/admin/finance/invoices/[id]", () => new FinanceReadService().invoice(gate.access, id), { op: "detail" });
  if (loaded.status === "not-found") notFound(); if (loaded.status !== "found") return <AdminDataUnavailableView active="invoices" role={gate.access.profile.role} />;
  const invoice = loaded.record, billing = invoice.billingCase, document = invoice.snapshot, returnTo = normalizeAdminReturnTo((await searchParams).returnTo, "/admin/finance/invoices"), settings = await new BillingSettingsService().load(gate.access);
  const sourceHref = billing.source.kind === "B2B" ? `/admin/inquiries/${billing.source.inquiryId}/billing` : `/admin/orders/${billing.source.orderId}`;
  const correction = !billing.closed && invoice.number && ["ISSUED", "VOID"].includes(invoice.state) && !invoice.replacementId && settings.values ? await loadAdminRecordLogged("page:/admin/finance/invoices/[id]", () => new FinanceReadService().source(gate.access, billing.source), { op: "correction-preview" }) : null;
  const fresh = correction?.status === "found" && !correction.record.snapshot.needsReview && settings.values ? { source: correction.record.snapshot, financial: buildInvoiceFinancialSnapshot(correction.record.snapshot, settings.values, { mode: billing.mode, depositRp: billing.depositRp, depositDueDate: document?.depositDueDate ?? null, balanceDueDate: document?.balanceDueDate ?? null }) } : null;
  const hidden = { invoiceId: id, expectedVersion: String(invoice.version), settingsVersion: String(settings.version), idempotencyKey: randomUUID() };
  return <AdminShell active="invoices" role={gate.access.profile.role}><main id="main-content" className="space-y-6" data-admin-surface="invoice-detail"><AdminPageHeader title={invoice.number ?? "Tinjau draft invoice"} description={`${FINANCE_STATE_LABELS[invoice.state]} · Revisi ${invoice.revision}`} returnHref={returnTo} returnLabel={adminRootLabel(returnTo) ?? "Invoice"} breadcrumbs={[{ label: "Keuangan", href: "/admin/finance" }, { label: "Invoice", href: "/admin/finance/invoices" }, { label: "Detail" }]} actions={invoice.number && !billing.closed ? <a className="inline-flex min-h-11 items-center rounded-lg border border-border bg-card px-4 text-sm font-semibold text-brand-700" href={`/api/admin/invoices/${id}/pdf`}>Unduh PDF</a> : null} />
    <div className="grid gap-4 sm:grid-cols-3">{[{ label: "Nilai dokumen", value: document?.totalRp ?? billing.totalRp }, { label: "Penerimaan terkonfirmasi", value: billing.paidRp }, { label: "Sisa tagihan proyek / pesanan", value: billing.remainingRp }].map(item => <Card as="section" key={item.label} className="gap-0 py-0 ring-0 min-w-0 rounded-xl border border-border bg-card p-5"><p className="text-xs text-muted-foreground">{item.label}</p><p className="mt-3 break-words text-xl font-semibold tabular-nums">{formatFinanceRp(item.value)}</p></Card>)}</div>
    {billing.closed ? <p className="rounded-lg border border-border bg-card p-4 text-sm text-muted-foreground">Identitas customer telah ditutup. Ringkasan keuangan dipertahankan; dokumen dengan identitas customer tidak tersedia.</p> : null}
    {billing.paymentState === "REVIEW" ? <p className="rounded-lg border border-warning-border bg-warning-background p-4 text-sm text-warning">Pembayaran atau sumber membutuhkan pemeriksaan. Penerimaan ditampilkan sebagai jumlah bruto terkonfirmasi, termasuk transaksi yang memiliki refund atau exception.</p> : null}
    {invoice.state === "VOID" && billing.paidRp !== "0" ? <p className="rounded-lg border border-warning-border bg-warning-background p-4 text-sm text-warning">Invoice dibatalkan dan penerimaan uang tetap terhubung ke pekerjaan ini. Tinjau tindak lanjut pembayaran.</p> : null}
    <Card as="section" className="gap-0 py-0 ring-0 space-y-5 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Rincian dokumen</h2>{invoice.buyer ? <div className="text-sm"><p className="font-semibold">{invoice.buyer.name}</p><p className="break-all text-muted-foreground">{invoice.buyer.email} · {invoice.buyer.phone}</p></div> : null}{document ? <><ul className="divide-y divide-border">{document.items.map((item, index) => <li className="flex min-w-0 flex-wrap justify-between gap-3 py-3 text-sm" key={index}><p className="min-w-0 flex-1 break-words">{item.name}</p><p className="font-semibold tabular-nums">{formatFinanceRp(item.amountRp)}</p></li>)}</ul><div className="grid min-w-0 gap-4 border-t border-border pt-4 text-sm md:grid-cols-2"><div><p className="font-semibold">Pola pembayaran</p><p className="mt-2">{document.mode === "FULL" ? "Pembayaran penuh" : `DP ${formatFinanceRp(document.depositRp ?? "0")} + pelunasan`}</p>{document.depositDueDate ? <p>Jatuh tempo DP: {document.depositDueDate}</p> : null}{document.balanceDueDate ? <p>Jatuh tempo: {document.balanceDueDate}</p> : null}</div><div className="min-w-0"><p className="font-semibold">Instruksi pembayaran</p>{invoicePaymentInstructions(document).map((line, index) => <p className="mt-2 whitespace-pre-wrap break-words text-muted-foreground" key={index}>{line}</p>)}</div></div></> : <p className="text-sm text-muted-foreground">Owner perlu melengkapi identitas penerbit dan rekening sebelum invoice diterbitkan.</p>}{!billing.closed ? <Link className="inline-flex min-h-11 items-center text-sm text-brand-700 underline" href={sourceHref}>Buka sumber pekerjaan</Link> : null}<div className="flex flex-wrap gap-4">{invoice.replacesId ? <Link className="inline-flex min-h-11 items-center text-sm text-brand-700 underline" href={`/admin/finance/invoices/${invoice.replacesId}`}>Invoice sebelumnya</Link> : null}{invoice.replacementId ? <Link className="inline-flex min-h-11 items-center text-sm text-brand-700 underline" href={`/admin/finance/invoices/${invoice.replacementId}`}>Invoice pengganti</Link> : null}</div>{invoice.reason ? <p className="text-sm text-muted-foreground">Alasan: {invoice.reason}</p> : null}</Card>
    {!billing.closed ? <div className="grid min-w-0 gap-5 xl:grid-cols-2">{invoice.state === "DRAFT" && document ? <Card as="section" className="gap-0 py-0 ring-0 space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Terbitkan invoice</h2><p className="text-sm text-muted-foreground">Tinjau penerima, rincian, dan instruksi pembayaran. Nomor invoice diberikan saat diterbitkan.</p><FinanceActionForm action={issueInvoiceAction} fields={[]} hidden={hidden} submitLabel="Terbitkan invoice" confirmMessage={`Terbitkan invoice ${formatFinanceRp(document.totalRp)} sesuai rincian yang ditinjau?`} /></Card> : null}{["DRAFT", "ISSUED"].includes(invoice.state) ? <Card as="section" className="gap-0 py-0 ring-0 space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Batalkan dokumen</h2><FinanceActionForm action={voidInvoiceAction} fields={[{ name: "reason", label: "Alasan pembatalan invoice", type: "textarea", required: true }]} hidden={hidden} submitLabel="Batalkan invoice" confirmMessage={`Batalkan dokumen ${invoice.number ?? "draft"}? Penerimaan uang tetap tersimpan dan tidak dikembalikan otomatis.`} /></Card> : null}{fresh ? <Card as="section" className="gap-0 py-0 ring-0 space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Terbitkan koreksi</h2><p className="text-sm text-muted-foreground">Invoice pengganti mengambil nilai sumber dan instruksi penerbit terbaru. Catatan uang tetap terhubung ke pekerjaan yang sama.</p><div className="rounded-lg border border-border bg-muted p-4 text-sm"><p className="font-semibold">Rincian invoice pengganti</p><p className="mt-2 break-words">{fresh.source.buyer.name} · {fresh.source.buyer.email}</p><ul className="mt-3 space-y-2">{fresh.financial.items.map((item, index) => <li key={index} className="flex flex-wrap justify-between gap-2"><span className="break-words">{item.name}</span><span>{formatFinanceRp(item.amountRp)}</span></li>)}</ul><p className="mt-3 font-semibold">Total {formatFinanceRp(fresh.financial.totalRp)}</p><p className="mt-3 break-words">{fresh.financial.issuer.issuerName}</p>{invoicePaymentInstructions(fresh.financial).map((line, index) => <p className="mt-2 whitespace-pre-wrap break-words" key={index}>{line}</p>)}</div><FinanceActionForm action={replaceInvoiceAction} fields={[{ name: "reason", label: "Alasan koreksi invoice", type: "textarea", required: true }]} hidden={{ ...hidden, expectedSourceVersion: fresh.source.sourceVersion }} submitLabel="Terbitkan invoice pengganti" confirmMessage="Terbitkan revisi dari sumber dan instruksi pembayaran terbaru dengan alasan ini? Dokumen sebelumnya tetap tersimpan." /></Card> : null}</div> : null}
  </main></AdminShell>;
}
