import { Card } from "@/components/ui/card";
import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { connection } from "next/server";
import { AdminPageHeader } from "@/app/admin/admin-page-header";
import { AdminAccessView } from "@/app/admin/admin-access-view";
import { loadAdminPageAccess } from "@/app/admin/admin-page-access";
import { loadAdminRecordLogged } from "@/app/admin/admin-page-failure";
import { AdminDataUnavailableView, AdminShell } from "@/components/niuva/admin-shell";
import { FinanceActionForm } from "@/components/niuva/finance-action-form";
import { B2BBillingService } from "@/modules/finance/b2b-billing-service";
import { BillingSettingsService } from "@/modules/finance/billing-settings-service";
import { recordB2BTransferAction, setB2BTermsAction } from "./actions";
const rp = (value: string) => `Rp ${BigInt(value).toLocaleString("id-ID")}`;
export default async function B2BBillingPage({ params }: Readonly<{ params: Promise<{ id: string }> }>) {
  await connection(); const gate = await loadAdminPageAccess({ permission: "FINANCE_READ" });
  if (gate.kind === "denied") return <AdminAccessView state={gate.state} />;
  const { id } = await params;
  const loaded = await loadAdminRecordLogged("page:/admin/inquiries/[id]/billing", () => new B2BBillingService().workspace(gate.access, id), { op: "read" });
  if (loaded.status === "not-found") notFound();
  if (loaded.status !== "found") return <AdminDataUnavailableView active="inquiries" role={gate.access.profile.role} />;
  const workspace = loaded.record, billing = workspace.billingCase;
  const settings = await new BillingSettingsService().load(gate.access);
  return <AdminShell active="inquiries" role={gate.access.profile.role}><main id="main-content" data-admin-surface="b2b-billing" className="space-y-6"><AdminPageHeader title="Penagihan proyek B2B" description={workspace.inquiry.reference} returnHref={`/admin/inquiries/${id}`} returnLabel="Detail B2B" breadcrumbs={[{ label: "B2B Inquiries", href: "/admin/inquiries" }, { label: "Penagihan" }]} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Nilai proyek", value: workspace.quote?.totalRp ?? "0" }, { label: "DP disepakati", value: billing?.depositRp ?? "0" }, { label: "Sudah diterima", value: billing?.paidRp ?? "0" }, { label: "Sisa tagihan", value: billing?.remainingRp ?? workspace.quote?.totalRp ?? "0" }].map(card => <Card as="section" key={card.label} className="gap-0 py-0 ring-0 min-w-0 rounded-xl border border-border bg-card p-5"><p className="text-xs text-muted-foreground">{card.label}</p><p className="mt-3 break-words text-xl font-semibold tabular-nums" data-billing-stat={card.label}>{rp(card.value)}</p></Card>)}</div>
    {billing?.paymentState === "REVIEW" ? <p className="rounded-lg border border-warning-border bg-warning-background p-4 text-sm text-warning">Sumber atau pembayaran memerlukan pemeriksaan Owner. Penerimaan uang tetap tersimpan pada proyek ini.</p> : null}
    <div className="grid min-w-0 gap-5 xl:grid-cols-2"><Card as="section" className="gap-0 py-0 ring-0 min-w-0 space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Pola pembayaran</h2>{workspace.quote?.status !== "ACCEPTED" ? <p className="text-sm text-muted-foreground">Tunggu proposal terbaru diterima customer sebelum menyiapkan penagihan.</p> : gate.access.profile.role === "OWNER" ? <FinanceActionForm action={setB2BTermsAction} hidden={{ inquiryId: id, acceptedQuoteId: workspace.quote.id, expectedVersion: String(billing?.version ?? 0), ...(settings.version ? { settingsVersion: String(settings.version), idempotencyKey: randomUUID() } : {}) }} fields={[{ name: "mode", label: "Cara pembayaran", type: "select", value: billing?.mode ?? "FULL", options: [{ value: "FULL", label: "Pembayaran penuh" }, { value: "DEPOSIT_BALANCE", label: "DP + pelunasan" }] }, { name: "depositRp", label: "Nominal DP (Rp)", value: billing?.depositRp ?? "", help: "Isi sesuai kesepakatan jika memilih DP + pelunasan." }, { name: "depositDueDate", label: "Jatuh tempo DP (opsional)", type: "date" }, { name: "balanceDueDate", label: "Jatuh tempo pembayaran / pelunasan (opsional)", type: "date" }, { name: "reason", label: "Alasan perubahan setelah invoice terbit", type: "textarea", help: "Perubahan setelah terbit menerbitkan invoice pengganti dan menyimpan riwayat." }]} submitLabel="Simpan pola pembayaran" confirmMessage="Terapkan pola pembayaran ini? Invoice terbit akan diganti melalui revisi dengan riwayat tersimpan." /> : <div className="space-y-3 text-sm"><p>{billing ? billing.mode === "FULL" ? "Pembayaran penuh" : "DP + pelunasan" : "Owner belum menentukan pola pembayaran."}</p><p className="text-muted-foreground">Pola pembayaran dan nominal DP ditentukan Owner.</p></div>}</Card>
      <Card as="section" className="gap-0 py-0 ring-0 min-w-0 space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Catat transfer terkonfirmasi</h2>{billing && billing.remainingRp !== "0" && billing.paymentState !== "REVIEW" ? <FinanceActionForm action={recordB2BTransferAction} hidden={{ inquiryId: id, billingCaseId: billing.id, expectedVersion: String(billing.version), idempotencyKey: randomUUID() }} fields={[{ name: "receivedDate", label: "Tanggal dana diterima", type: "date", required: true }, { name: "amountRp", label: "Nominal diterima (Rp)", required: true }, { name: "reference", label: "Referensi transfer", required: true, maxLength: 100 }, { name: "note", label: "Catatan (opsional)", type: "textarea" }, { name: "confirmed", label: "Saya sudah mencocokkan dana masuk dengan tagihan", type: "checkbox", required: true }]} submitLabel="Catat pembayaran" /> : <p className="text-sm text-muted-foreground">{billing?.remainingRp === "0" ? "Tagihan sudah terpenuhi. Riwayat penerimaan tetap dapat ditinjau." : "Tentukan pola pembayaran dan selesaikan pemeriksaan sumber terlebih dahulu."}</p>}</Card></div>
    {billing ? <Card as="section" className="gap-0 py-0 ring-0 space-y-3 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Invoice proyek</h2><p className="text-sm text-muted-foreground">Satu invoice untuk nilai proyek; DP dan pelunasan dicatat sebagai penerimaan pada proyek yang sama.</p><Link className="inline-flex min-h-11 items-center text-sm text-brand-700 underline" href={billing.currentInvoiceId ? `/admin/finance/invoices/${billing.currentInvoiceId}` : `/admin/finance/invoices/new?kind=B2B&sourceId=${id}`}>{billing.currentInvoiceId ? "Buka invoice proyek" : "Siapkan invoice proyek"}</Link></Card> : null}
    <Card as="section" className="gap-0 py-0 ring-0 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Riwayat transfer</h2><p className="mt-1 text-sm text-muted-foreground">Koreksi mengubah pencatatan dan menyimpan catatan asli. Pengembalian uang dilakukan terpisah.</p>{workspace.transfers.length ? <ul className="mt-4 divide-y divide-border">{workspace.transfers.map(payment => <li className="flex min-w-0 flex-wrap justify-between gap-3 py-4" key={payment.id}><div className="min-w-0"><Link className="inline-flex min-h-11 items-center break-all text-sm font-medium text-brand-700 hover:underline" href={`/admin/finance/payments/${payment.id}`}>{payment.reference}</Link><p className="text-xs text-muted-foreground">{payment.actualDate} · {payment.state === "CONFIRMED" ? "Terkonfirmasi" : payment.state === "REVERSAL" ? "Pembatalan pencatatan" : "Dikoreksi / dibatalkan"}</p></div><p className="text-sm font-semibold tabular-nums">{rp(payment.amountRp)}</p></li>)}</ul> : <p className="py-6 text-sm text-muted-foreground">Belum ada transfer terkonfirmasi.</p>}<Link className="inline-flex min-h-11 items-center text-sm text-brand-700 underline" href={`/admin/inquiries/${id}/proposal`}>Tinjau proposal sumber</Link></Card>
  </main></AdminShell>;
}
