"use client";
import { useActionState, useState } from "react";
import { Button } from "@/components/ui/button";
import { useHydrated } from "@/components/niuva/use-hydrated";
import { siteInformationSchema } from "@/modules/site-information/schema";
import type { SiteInformationActionState, SiteInformationSnapshot } from "@/modules/site-information/types";
const control = "min-h-11 w-full min-w-0 rounded-lg border border-input bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50";
export function SiteInformationForm({ snapshot, action }: Readonly<{ snapshot: SiteInformationSnapshot; action: (previous: SiteInformationActionState, data: FormData) => Promise<SiteInformationActionState> }>) {
  const hydrated = useHydrated();
  const [values, setValues] = useState(snapshot.values);
  const [preview, setPreview] = useState(false);
  const [state, formAction, pending] = useActionState(action, { status: "idle" });
  const validated = siteInformationSchema.safeParse(values);
  const update = (key: "shortDescription" | "email" | "phone" | "address", value: string) => { setValues(previous => ({ ...previous, [key]: value })); setPreview(false); };
  return <form action={formAction} className="space-y-5">
    <input type="hidden" name="payload" value={JSON.stringify({ expectedVersion: state.version ?? snapshot.version, values })} />
    <fieldset className="space-y-5" disabled={pending || !hydrated}>
      <section className="space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Profil</h2><p className="text-sm text-muted-foreground">Deskripsi ditampilkan di halaman utama dan footer situs.</p><label className="grid gap-2 text-sm font-medium">Deskripsi singkat<textarea className={control} maxLength={600} rows={4} value={values.shortDescription} onChange={event => update("shortDescription", event.target.value)} required /></label></section>
      <section className="space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Kontak</h2><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Email<input className={control} type="email" maxLength={254} value={values.email} onChange={event => update("email", event.target.value)} required /></label><label className="grid gap-2 text-sm font-medium">Telepon / WhatsApp<input className={control} type="tel" maxLength={30} value={values.phone} onChange={event => update("phone", event.target.value)} required /></label></div><label className="grid gap-2 text-sm font-medium">Alamat<textarea className={control} rows={3} maxLength={600} value={values.address} onChange={event => update("address", event.target.value)} required /></label></section>
      <section className="space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Media sosial</h2><p className="text-sm text-muted-foreground">Tautan HTTPS yang diterbitkan muncul di footer.</p>{values.socialLinks.map((link, index) => <div key={index} className="grid min-w-0 gap-3 sm:grid-cols-[1fr_2fr_auto]"><label className="grid gap-2 text-sm">Nama tautan {index + 1}<input className={control} maxLength={40} value={link.label} onChange={event => setValues(previous => ({ ...previous, socialLinks: previous.socialLinks.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item) }))} required /></label><label className="grid gap-2 text-sm">URL {index + 1}<input className={control} type="url" maxLength={500} value={link.href} onChange={event => setValues(previous => ({ ...previous, socialLinks: previous.socialLinks.map((item, itemIndex) => itemIndex === index ? { ...item, href: event.target.value } : item) }))} required /></label><Button className="self-end" type="button" variant="outline" onClick={() => setValues(previous => ({ ...previous, socialLinks: previous.socialLinks.filter((_, itemIndex) => itemIndex !== index) }))}>Hapus</Button></div>)}<Button type="button" variant="outline" disabled={values.socialLinks.length >= 8} onClick={() => setValues(previous => ({ ...previous, socialLinks: [...previous.socialLinks, { label: "", href: "https://" }] }))}>Tambah tautan</Button></section>
      {!validated.success ? <p className="text-sm text-destructive" role="status">Periksa deskripsi, kontak, dan tautan HTTPS sebelum menerbitkan.</p> : null}
      <div className="flex flex-wrap gap-3"><Button type="button" variant="outline" disabled={!validated.success} onClick={() => setPreview(value => !value)}>Pratinjau</Button><Button type="submit" disabled={!validated.success || pending}>{pending ? "Menerbitkan…" : "Terbitkan perubahan"}</Button></div>
    </fieldset>
    {preview && validated.success ? <section className="space-y-3 rounded-xl border border-brand-200 bg-card p-5" aria-labelledby="site-preview-title"><h2 id="site-preview-title" className="text-lg font-semibold">Pratinjau informasi publik</h2><p>{values.shortDescription}</p><address className="space-y-2 break-words text-sm not-italic text-muted-foreground"><p>{values.address}</p><p>{values.email}</p><p>{values.phone}</p></address>{values.socialLinks.map(link => <a key={link.href} className="mr-4 inline-flex min-h-11 items-center text-sm text-brand-700 underline" href={link.href} target="_blank" rel="noopener noreferrer">{link.label}</a>)}</section> : null}
    {state.message ? <p className={`rounded-lg border p-4 text-sm ${state.status === "error" ? "border-destructive-border bg-destructive-background text-destructive" : "border-success-border bg-success-background text-success"}`} role={state.status === "error" ? "alert" : "status"}>{state.message}</p> : null}
  </form>;
}
